### PR TITLE
Modified the UI , added a download button and Copy Button

### PR DESCRIPTION
**Pull request by Lucky-victory**
Modified the User Interface, added copy to clipboard button , also the ability to download the svg as a .svg file.

### CODE REVIEW

**Comment by danmarshall** [comment]
Hi @Lucky-victory , thanks a lot! Can you add a screenshot of what it looks like, to save me some time?

**Comment by Lucky-victory** [comment]
Alright, here's the screenshot
Screenshot_20210516-175328_1

**Comment by danmarshall** [comment]
Thanks! Now there is one other issue - the `index.js` file id generated from the Typescript file `index.ts`. Can you make your changes in the `.ts` file?

**Comment by Lucky-victory** [comment]
Sure, let me fix that

**Comment by Lucky-victory** [comment]
done

**Comment by danmarshall** [comment]
Can we leave the `<h1>Google font to SVG path</h1>` as text? I'd like to keep it SEO friendly.

**Comment by Lucky-victory** [comment]
that's right.

**Comment by Lucky-victory** [comment]
done

**Comment by danmarshall** [comment]
Thanks!

**Pull request merged**
